### ISSUE TITLE
.metadata non va su github !

### ISSUE THREAD

**Issue by garganti** [mangilimatteo/Progetto_Ingegneria_Software_Cattaneo_Mangili_Saini#3]

**Comment by garganti** [comment]
la struttura del repo è un po' tutta caotica. Il codice mettetelo in un folder per il codice, la documentazione da un'altra parte.

**Comment by garganti** [comment]
ATTENZIONE .metadata non va su github !!!

**Comment by mangilimatteo** [comment]
operazione effettuata: eliminazione .metadata dal branch principale
