### ISSUE TITLE
Consegna Project Plan

### ISSUE THREAD

**Issue by mangilimatteo** [mangilimatteo/Progetto_Ingegneria_Software_Cattaneo_Mangili_Saini#5]
Consegna Project Plan del Progetto: si faccia riferimento al branch main, cartella "Documentazione"

**Comment by garganti** [comment]
ci sino 3 project plan, 1 un doc l'altro un md penso, una final ... quale prendo?

**Comment by mangilimatteo** [comment]
Abbiamo avuto problemi a caricare versioni non aggiornate dal branch Main; ora abbiamo risolto risolto.
Il Project Plan si trova nel branch di Default Main nalla cartella Documentazione

**Comment by garganti** [comment]
ok per me
