### ISSUE TITLE
Ricarica Versione

### ISSUE THREAD

**Issue by Marco-Saini** [mangilimatteo/Progetto_Ingegneria_Software_Cattaneo_Mangili_Saini#6]
#5  Dato il seguente problema, ho controllato ed é stato caricato in main una vecchia versione.
Quindi ti ho creato un branch "VeroMain" di backup, controlla se era la versione che volevi e modificala come branch di default
(settings->default branch clicca freccia "di scambio" -> Update).

Una volta fatto rinomina pure il branch.

Inoltre non dimenticare di aggiornare il docente.

**Comment by mangilimatteo** [comment]
Creazione nuovo branch principale
