### ISSUE TITLE
Link DB e GUI

### ISSUE THREAD

**Issue by Marco-Saini** [mangilimatteo/Progetto_Ingegneria_Software_Cattaneo_Mangili_Saini#7]
Ho realizzato parzialmente la GUI il file piú avanzato é il pannello pazienti e su quell' esempio creeró il verbale.

Rimane ancora da collegare il DB, che da concordato lo lascio svolgere a te.
Tienimi aggiornato su come ti sembra.

**Comment by mangilimatteo** [comment]
Ho capito, ma dove si trovano sul branch, che non li trovo?
